filebeat.inputs:
  - type: log
    enabled: true
    paths:
      - /usr/local/share/logs/app-logs/*.log
    fields:
      destination: laravel-in-docker-log
    fields_under_root: true

  - type: log
    enabled: true
    paths:
      - /usr/local/share/logs/nginx-logs/*.log
    fields:
      destination: laravel-nginx-log
    fields_under_root: true

filebeat.config:
  modules:
    path: ${path.config}/modules.d/*.yml
    reload.enabled: false

processors:
  - add_cloud_metadata: ~
  - add_docker_metadata: ~

output.kafka:
  enabled: true
  hosts: ["kafka:9092"]
  #要提前创建topic
  topic: "%{[destination]}"
  partition.hash:
    reachable_only: true
  compression: gzip
  max_message_bytes: 1000000
  required_acks: 1

